import { describe, expect, it } from 'vitest';
import { renderPrComment } from '../src/comment-renderer.js';
import type { RenderAuthorInput } from '../src/comment-renderer.js';

const currentAuthor: RenderAuthorInput = {
  login: 'samuel',
  totalCostUsd: 4.83,
  inputTokens: 2_100_000,
  outputTokens: 184_000,
  cacheWriteTokens: 0,
  cacheReadTokens: 0,
  sessionCount: 3,
  models: ['claude-sonnet-4-6', 'claude-opus-4-8'],
  attributedPercent: 91,
  lowConfidencePercent: 7,
  rows: [
    {
      sha: 'aaa1111',
      message: 'first commit',
      inputTokens: 1_000_000,
      outputTokens: 100_000,
      costUsd: 2.3,
      sessionCount: 1,
    },
    {
      sha: 'bbb2222',
      message: 'second commit',
      inputTokens: 1_100_000,
      outputTokens: 84_000,
      costUsd: 2.53,
      sessionCount: 2,
    },
    {
      sha: 'uncommitted',
      message: 'uncommitted tail',
      inputTokens: 0,
      outputTokens: 0,
      costUsd: 0,
      sessionCount: 0,
    },
  ],
};

describe('renderPrComment', () => {
  it('renders a new PR token cost comment for the current author', () => {
    const body = renderPrComment({ existingBody: undefined, currentAuthor });

    expect(body).toContain('<!-- prtokens:v1 -->');
    expect(body).toContain('🪙 **This PR cost ~$4.83 in tokens**');
    expect(body).toContain('2.1M in / 184k out');
    expect(body).toContain('3 sessions');
    expect(body).toContain('91% attributed');
    expect(body).toContain('<details>');
    expect(body).toContain('| `aaa1111` | first commit | 1M | 100k | ~$2.30 | 1 |');
    expect(body).toContain('*estimated at API rates · generated by prtokens*');
  });

  it('preserves another author section and recomputes the combined total', () => {
    const alexSummary = {
      login: 'alex',
      totalCostUsd: 1,
      inputTokens: 100_000,
      outputTokens: 10_000,
      sessionCount: 1,
      models: ['claude-sonnet-4-6'],
      attributedPercent: 100,
      lowConfidencePercent: 0,
    };
    const existingBody = [
      '<!-- prtokens:v1 -->',
      '🪙 **This PR cost ~$1.00 in tokens**',
      '',
      `<!-- prtokens:author:alex ${JSON.stringify(alexSummary)} -->`,
      '### @alex',
      '',
      '100k in / 10k out · 1 session · 100% attributed',
      '',
      '*estimated at API rates · generated by prtokens*',
    ].join('\n');

    const body = renderPrComment({ existingBody, currentAuthor });

    expect(body).toContain('<!-- prtokens:author:alex ');
    expect(body).toContain('### @alex');
    expect(body).toContain('<!-- prtokens:author:samuel ');
    expect(body).toContain('### @samuel');
    expect(body).toContain('🪙 **This PR cost ~$5.83 in tokens**');
  });
});
