import { describe, expect, it } from 'vitest';
import { renderPrComment } from '../src/comment-renderer.js';
import type { RenderAuthorInput } from '../src/comment-renderer.js';

const currentAuthor: RenderAuthorInput = {
  login: 'samuel',
  totalCostUsd: 4.83,
  inputTokens: 2_100_000,
  outputTokens: 184_000,
  cacheWriteTokens: 0,
  cacheReadTokens: 0,
  sessionCount: 3,
  models: ['claude-sonnet-4-6', 'claude-opus-4-8'],
  attributedPercent: 91,
  lowConfidencePercent: 7,
  rows: [
    {
      sha: 'aaa1111',
      message: 'first commit',
      inputTokens: 1_000_000,
      outputTokens: 100_000,
      costUsd: 2.3,
      sessionCount: 1,
    },
    {
      sha: 'bbb2222',
      message: 'second commit',
      inputTokens: 1_100_000,
      outputTokens: 84_000,
      costUsd: 2.53,
      sessionCount: 2,
    },
    {
      sha: 'uncommitted',
      message: 'uncommitted tail',
      inputTokens: 0,
      outputTokens: 0,
      costUsd: 0,
      sessionCount: 0,
    },
  ],
};

function authorMarkerPayload(body: string, login: string): string {
  const markerLine = body.split('\n').find((line) => line.startsWith(`<!-- prtokens:author:${login} `));
  expect(markerLine).toBeDefined();

  return markerLine!
    .slice(`<!-- prtokens:author:${login} `.length)
    .replace(/ -->$/, '');
}

describe('renderPrComment', () => {
  it('renders a new PR token cost comment for the current author', () => {
    const body = renderPrComment({ existingBody: undefined, currentAuthor });

    expect(body).toContain('<!-- prtokens:v1 -->');
    expect(body).toContain('🪙 **This PR cost ~$4.83 in tokens**');
    expect(body).toContain('2.1M in / 184k out');
    expect(body).toContain('3 sessions');
    expect(body).toContain('91% attributed');
    expect(body).toContain('<details>');
    expect(body).toContain('| `aaa1111` | first commit | 1M | 100k | ~$2.30 | 1 |');
    expect(body).toContain('*estimated at API rates · generated by prtokens*');
  });

  it('preserves another author section and recomputes the combined total', () => {
    const alexSummary = {
      login: 'alex',
      totalCostUsd: 1,
      inputTokens: 100_000,
      outputTokens: 10_000,
      sessionCount: 1,
      models: ['claude-sonnet-4-6'],
      attributedPercent: 100,
      lowConfidencePercent: 0,
    };
    const existingBody = [
      '<!-- prtokens:v1 -->',
      '🪙 **This PR cost ~$1.00 in tokens**',
      '',
      `<!-- prtokens:author:alex ${JSON.stringify(alexSummary)} -->`,
      '### @alex',
      '',
      '100k in / 10k out · 1 session · 100% attributed',
      '',
      '*estimated at API rates · generated by prtokens*',
    ].join('\n');

    const body = renderPrComment({ existingBody, currentAuthor });

    expect(body).toContain('<!-- prtokens:author:alex ');
    expect(body).toContain('### @alex');
    expect(body).toContain('<!-- prtokens:author:samuel ');
    expect(body).toContain('### @samuel');
    expect(body).toContain('🪙 **This PR cost ~$5.83 in tokens**');
  });

  it('preserves another author details table when updating the current author', () => {
    const alexAuthor: RenderAuthorInput = {
      login: 'alex',
      totalCostUsd: 1,
      inputTokens: 100_000,
      outputTokens: 10_000,
      cacheWriteTokens: 0,
      cacheReadTokens: 0,
      sessionCount: 1,
      models: ['claude-sonnet-4-6'],
      attributedPercent: 100,
      lowConfidencePercent: 0,
      rows: [
        {
          sha: 'abc9999',
          message: 'alex unique detail row',
          inputTokens: 100_000,
          outputTokens: 10_000,
          costUsd: 1,
          sessionCount: 1,
        },
      ],
    };
    const existingBody = renderPrComment({ currentAuthor: alexAuthor });

    const body = renderPrComment({ existingBody, currentAuthor });

    expect(body).toContain('| `abc9999` | alex unique detail row | 100k | 10k | ~$1.00 | 1 |');
    expect(body).toContain('<!-- prtokens:author:samuel ');
    expect(body).toContain('| `aaa1111` | first commit | 1M | 100k | ~$2.30 | 1 |');
    expect(body).toContain('🪙 **This PR cost ~$5.83 in tokens**');
  });

  it('does not truncate a preserved section when a row contains footer text', () => {
    const alexAuthor: RenderAuthorInput = {
      login: 'alex',
      totalCostUsd: 1,
      inputTokens: 100_000,
      outputTokens: 10_000,
      cacheWriteTokens: 0,
      cacheReadTokens: 0,
      sessionCount: 1,
      models: ['claude-sonnet-4-6'],
      attributedPercent: 100,
      lowConfidencePercent: 0,
      rows: [
        {
          sha: 'feed123',
          message: 'mentions *estimated at API rates · generated by prtokens* inside a commit',
          inputTokens: 100_000,
          outputTokens: 10_000,
          costUsd: 1,
          sessionCount: 1,
        },
      ],
    };
    const existingBody = renderPrComment({ currentAuthor: alexAuthor });

    const body = renderPrComment({ existingBody, currentAuthor });

    expect(body).toContain(
      '| `feed123` | mentions *estimated at API rates · generated by prtokens* inside a commit | 100k | 10k | ~$1.00 | 1 |',
    );
    expect(body).toContain('| `aaa1111` | first commit | 1M | 100k | ~$2.30 | 1 |');
  });

  it('escapes author marker JSON so comment delimiters in values remain parseable', () => {
    const unsafeAuthor: RenderAuthorInput = {
      login: 'unsafe',
      totalCostUsd: 1,
      inputTokens: 100_000,
      outputTokens: 10_000,
      cacheWriteTokens: 0,
      cacheReadTokens: 0,
      sessionCount: 1,
      models: ['claude-->unsafe'],
      attributedPercent: 100,
      lowConfidencePercent: 0,
      rows: [],
    };

    const existingBody = renderPrComment({ currentAuthor: unsafeAuthor });
    const payload = authorMarkerPayload(existingBody, 'unsafe');

    expect(payload).not.toContain('-->');
    expect(JSON.parse(payload)).toMatchObject({ login: 'unsafe', models: ['claude-->unsafe'] });

    const body = renderPrComment({ existingBody, currentAuthor });
    expect(body).toContain('Models: `claude-->unsafe`');
    expect(body).toContain('🪙 **This PR cost ~$5.83 in tokens**');
  });

  it('ignores malformed author marker JSON', () => {
    const existingBody = [
      '<!-- prtokens:v1 -->',
      '🪙 **This PR cost ~$99.00 in tokens**',
      '',
      '<!-- prtokens:author:broken {not json} -->',
      '### @broken',
      '',
      'This malformed section should not be carried forward.',
      '',
      '*estimated at API rates · generated by prtokens*',
    ].join('\n');

    const body = renderPrComment({ existingBody, currentAuthor });

    expect(body).not.toContain('This malformed section should not be carried forward.');
    expect(body).not.toContain('prtokens:author:broken');
    expect(body).toContain('🪙 **This PR cost ~$4.83 in tokens**');
  });

  it('escapes pipes and newlines in table messages', () => {
    const body = renderPrComment({
      currentAuthor: {
        ...currentAuthor,
        rows: [
          {
            sha: 'pipe123',
            message: 'message with | pipe\nand newline',
            inputTokens: 1,
            outputTokens: 2,
            costUsd: 0.01,
            sessionCount: 1,
          },
        ],
      },
    });

    expect(body).toContain('| `pipe123` | message with \\| pipe<br>and newline | 1 | 2 | ~$0.01 | 1 |');
  });

  it('formats zero tokens, singular sessions, and no models', () => {
    const body = renderPrComment({
      currentAuthor: {
        ...currentAuthor,
        totalCostUsd: 0,
        inputTokens: 0,
        outputTokens: 0,
        sessionCount: 1,
        models: [],
        rows: [],
      },
    });

    expect(body).toContain('0 in / 0 out · 1 session');
    expect(body).toContain('Models: none');
  });
});
