export interface RenderAgentInput {
  agent: string;
  costUsd: number;
  inputTokens: number;
  outputTokens: number;
  sessionCount: number;
}

export interface RenderAuthorInput {
  login: string;
  totalCostUsd: number;
  inputTokens: number;
  outputTokens: number;
  cacheWriteTokens: number;
  cacheReadTokens: number;
  sessionCount: number;
  models: string[];
  agents?: RenderAgentInput[];
  attributedPercent: number;
  lowConfidencePercent: number;
  rows: Array<{
    sha: string;
    message: string;
    inputTokens: number;
    outputTokens: number;
    cacheWriteTokens: number;
    cacheReadTokens: number;
    costUsd: number;
    sessionCount: number;
  }>;
}

export interface RenderPrCommentInput {
  existingBody?: string;
  currentAuthor: RenderAuthorInput;
}

type AuthorSummary = Pick<
  RenderAuthorInput,
  | 'login'
  | 'totalCostUsd'
  | 'inputTokens'
  | 'outputTokens'
  | 'sessionCount'
  | 'models'
  | 'agents'
  | 'attributedPercent'
  | 'lowConfidencePercent'
>;

interface AuthorSection {
  summary: AuthorSummary;
  section: string;
}

export const COMMENT_MARKER = '<!-- prtokens:v1 -->';

const FOOTER = '*generated by prtokens*';
const RECOGNIZED_FOOTERS = [
  FOOTER,
  '*uses agent-reported costs when available; otherwise estimates from token pricing \u00b7 generated by prtokens*',
  '*cost uses source-reported values when available; otherwise estimated from token pricing \u00b7 generated by prtokens*',
  '*estimated at API rates \u00b7 generated by prtokens*',
];

export function renderPrComment(input: RenderPrCommentInput): string {
  const existingAuthors = parseAuthorSections(input.existingBody ?? '');
  const currentSummary = toAuthorSummary(input.currentAuthor);
  const willReplace = existingAuthors.some((author) => author.summary.login === currentSummary.login);
  const authorCount = willReplace ? existingAuthors.length : existingAuthors.length + 1;
  const authors = replaceCurrentAuthor(existingAuthors, input.currentAuthor, currentSummary, authorCount > 1);
  const totalCostUsd = authors.reduce((sum, author) => sum + author.summary.totalCostUsd, 0);

  return [
    COMMENT_MARKER,
    `### ${'\u{1FA99}'} This PR cost ${formatCost(totalCostUsd)} in tokens`,
    '',
    ...authors.flatMap((author) => [normalizeAuthorSection(author, authorCount > 1), '']),
    FOOTER,
  ].join('\n');
}

function normalizeAuthorSection(author: AuthorSection, showAuthorLabel: boolean): string {
  if (!showAuthorLabel || authorSectionHasVisibleLabel(author)) return author.section;

  const [marker, ...rest] = author.section.split('\n');
  return [marker, `**@${author.summary.login}** · ${formatCost(author.summary.totalCostUsd)}`, '', ...rest].join('\n');
}

function authorSectionHasVisibleLabel(author: AuthorSection): boolean {
  const lines = author.section.split('\n');
  const markerIndex = lines.findIndex((line) => line.startsWith(`<!-- prtokens:author:${author.summary.login} `));
  const nextLine = markerIndex === -1 ? undefined : lines[markerIndex + 1];

  return nextLine === `### @${author.summary.login}` || nextLine === `**@${author.summary.login}** · ${formatCost(author.summary.totalCostUsd)}`;
}

function replaceCurrentAuthor(
  existingAuthors: AuthorSection[],
  currentAuthor: RenderAuthorInput,
  currentSummary: AuthorSummary,
  showAuthorLabel: boolean,
): AuthorSection[] {
  let replaced = false;
  const currentSection = renderCurrentAuthorSection(currentAuthor, currentSummary, showAuthorLabel).join('\n').trimEnd();
  const authors = existingAuthors.map((author) => {
    if (author.summary.login !== currentSummary.login) return author;
    replaced = true;
    return { summary: currentSummary, section: currentSection };
  });

  if (!replaced) authors.push({ summary: currentSummary, section: currentSection });
  return authors;
}

function parseAuthorSections(body: string): AuthorSection[] {
  const sections: AuthorSection[] = [];
  const markerPattern = /^<!-- prtokens:author:([^\s]+) (.+) -->$/gm;
  const markers = Array.from(body.matchAll(markerPattern));

  for (const [index, match] of markers.entries()) {
    try {
      const parsed: unknown = JSON.parse(match[2] ?? '');
      if (!isAuthorSummary(parsed) || match.index === undefined) continue;

      const nextMarker = markers[index + 1];
      const nextFooter = findFooterLineIndex(body, match.index);
      const nextSectionStart = nextMarker?.index ?? body.length;
      const sectionEnd = nextFooter === -1 ? nextSectionStart : Math.min(nextSectionStart, nextFooter);

      sections.push({
        summary: parsed,
        section: body.slice(match.index, sectionEnd).trimEnd(),
      });
    } catch {
      // Ignore malformed markers so a broken previous comment does not block rendering.
    }
  }

  return sections;
}

function findFooterLineIndex(body: string, start: number): number {
  let earliestFooterIndex = -1;

  for (const footer of RECOGNIZED_FOOTERS) {
    const index = findFooterLineIndexForText(body, start, footer);
    if (index !== -1 && (earliestFooterIndex === -1 || index < earliestFooterIndex)) {
      earliestFooterIndex = index;
    }
  }

  return earliestFooterIndex;
}

function findFooterLineIndexForText(body: string, start: number, footer: string): number {
  let searchFrom = start;

  while (searchFrom < body.length) {
    const index = body.indexOf(footer, searchFrom);
    if (index === -1) return -1;

    const previous = body[index - 1];
    const next = body[index + footer.length];
    if ((previous === undefined || previous === '\n' || previous === '\r') && (next === undefined || next === '\n' || next === '\r')) {
      return index;
    }

    searchFrom = index + footer.length;
  }

  return -1;
}

function isAuthorSummary(value: unknown): value is AuthorSummary {
  if (!value || typeof value !== 'object') return false;
  const summary = value as Record<string, unknown>;

  return (
    typeof summary.login === 'string' &&
    typeof summary.totalCostUsd === 'number' &&
    typeof summary.inputTokens === 'number' &&
    typeof summary.outputTokens === 'number' &&
    typeof summary.sessionCount === 'number' &&
    Array.isArray(summary.models) &&
    summary.models.every((model) => typeof model === 'string') &&
    (summary.agents === undefined || (Array.isArray(summary.agents) && summary.agents.every(isRenderAgentInput))) &&
    typeof summary.attributedPercent === 'number' &&
    typeof summary.lowConfidencePercent === 'number'
  );
}

function isRenderAgentInput(value: unknown): value is RenderAgentInput {
  if (!value || typeof value !== 'object') return false;
  const agent = value as Record<string, unknown>;

  return (
    typeof agent.agent === 'string' &&
    typeof agent.costUsd === 'number' &&
    typeof agent.inputTokens === 'number' &&
    typeof agent.outputTokens === 'number' &&
    typeof agent.sessionCount === 'number'
  );
}

function toAuthorSummary(author: RenderAuthorInput): AuthorSummary {
  const summary: AuthorSummary = {
    login: author.login,
    totalCostUsd: author.totalCostUsd,
    inputTokens: author.inputTokens,
    outputTokens: author.outputTokens,
    sessionCount: author.sessionCount,
    models: author.models,
    attributedPercent: author.attributedPercent,
    lowConfidencePercent: author.lowConfidencePercent,
  };

  if (author.agents !== undefined) summary.agents = author.agents;
  return summary;
}

function renderCurrentAuthorSection(author: RenderAuthorInput, summary: AuthorSummary, showAuthorLabel: boolean): string[] {
  return [
    authorMarker(summary),
    ...(showAuthorLabel ? [`**@${author.login}** · ${formatCost(summary.totalCostUsd)}`, ''] : []),
    renderSummaryLine(summary),
    '',
    renderModels(summary.models),
    ...renderAgents(summary.agents),
    '',
    '<details>',
    '<summary>Commit breakdown</summary>',
    '',
    '| Commit | Message | In | Out | Cost | Sessions |',
    '| --- | --- | ---: | ---: | ---: | ---: |',
    ...author.rows.map(
      (row) =>
        `| \`${truncateSha(row.sha)}\` | ${escapeTableCell(row.message)} | ${formatTokens(row.inputTokens)} | ${formatTokens(
          row.outputTokens,
        )} | ${formatCost(row.costUsd)} | ${row.sessionCount} |`,
    ),
    '',
    '</details>',
    '',
  ];
}

function authorMarker(summary: AuthorSummary): string {
  return `<!-- prtokens:author:${summary.login} ${htmlCommentSafeJson(summary)} -->`;
}

function htmlCommentSafeJson(value: AuthorSummary): string {
  return JSON.stringify(value).replace(/-/g, '\\u002d').replace(/</g, '\\u003c').replace(/>/g, '\\u003e');
}

function renderSummaryLine(summary: AuthorSummary): string {
  return `${formatTokens(summary.inputTokens)} in / ${formatTokens(summary.outputTokens)} out \u00b7 ${formatSessions(
    summary.sessionCount,
  )}`;
}

function renderModels(models: string[]): string {
  if (models.length === 0) return 'Models: none';
  if (models.length === 1) return `Model: \`${models[0]}\``;
  return `Models: ${models.map((model) => `\`${model}\``).join(', ')}`;
}

function renderAgents(agents: RenderAgentInput[] | undefined): string[] {
  if (agents === undefined || agents.length === 0) return [];
  const sortedAgents = [...agents].sort((left, right) => right.costUsd - left.costUsd);
  if (sortedAgents.length === 1) return [`Agent: \`${sortedAgents[0].agent}\``];
  return [`Agents: ${sortedAgents.map((agent) => `\`${agent.agent}\` ${formatCost(agent.costUsd)}`).join(' · ')}`];
}

function formatCost(costUsd: number): string {
  return `~$${costUsd.toFixed(2)}`;
}

function formatTokens(tokens: number): string {
  if (tokens === 0) return '0';
  if (tokens >= 1_000_000) return `${trimTrailingZero(tokens / 1_000_000)}M`;
  if (tokens >= 1_000) return `${trimTrailingZero(tokens / 1_000)}k`;
  return String(tokens);
}

function trimTrailingZero(value: number): string {
  return value.toFixed(1).replace(/\.0$/, '');
}

function formatSessions(sessionCount: number): string {
  return `${sessionCount} ${sessionCount === 1 ? 'session' : 'sessions'}`;
}

function truncateSha(sha: string): string {
  return sha.slice(0, 7);
}

function escapeTableCell(value: string): string {
  return value.replace(/\r?\n/g, '<br>').replace(/\|/g, '\\|');
}
