export interface RenderAuthorInput {
  login: string;
  totalCostUsd: number;
  inputTokens: number;
  outputTokens: number;
  cacheWriteTokens: number;
  cacheReadTokens: number;
  sessionCount: number;
  models: string[];
  attributedPercent: number;
  lowConfidencePercent: number;
  rows: Array<{
    sha: string;
    message: string;
    inputTokens: number;
    outputTokens: number;
    costUsd: number;
    sessionCount: number;
  }>;
}

export interface RenderPrCommentInput {
  existingBody?: string;
  currentAuthor: RenderAuthorInput;
}

type AuthorSummary = Pick<
  RenderAuthorInput,
  | 'login'
  | 'totalCostUsd'
  | 'inputTokens'
  | 'outputTokens'
  | 'sessionCount'
  | 'models'
  | 'attributedPercent'
  | 'lowConfidencePercent'
>;

export const COMMENT_MARKER = '<!-- prtokens:v1 -->';

const FOOTER = '*estimated at API rates \u00b7 generated by prtokens*';

export function renderPrComment(input: RenderPrCommentInput): string {
  const existingAuthors = parseAuthorSummaries(input.existingBody ?? '');
  const currentSummary = toAuthorSummary(input.currentAuthor);
  const authors = replaceCurrentAuthor(existingAuthors, currentSummary);
  const totalCostUsd = authors.reduce((sum, author) => sum + author.totalCostUsd, 0);

  return [
    COMMENT_MARKER,
    `${'\u{1FA99}'} **This PR cost ${formatCost(totalCostUsd)} in tokens**`,
    '',
    ...authors.flatMap((author) =>
      author.login === currentSummary.login
        ? renderCurrentAuthorSection(input.currentAuthor, currentSummary)
        : renderAuthorSummarySection(author),
    ),
    FOOTER,
  ].join('\n');
}

function replaceCurrentAuthor(existingAuthors: AuthorSummary[], currentSummary: AuthorSummary): AuthorSummary[] {
  let replaced = false;
  const authors = existingAuthors.map((author) => {
    if (author.login !== currentSummary.login) return author;
    replaced = true;
    return currentSummary;
  });

  if (!replaced) authors.push(currentSummary);
  return authors;
}

function parseAuthorSummaries(body: string): AuthorSummary[] {
  const summaries: AuthorSummary[] = [];
  const markerPattern = /^<!-- prtokens:author:([^\s]+) (.+) -->$/gm;

  for (const match of body.matchAll(markerPattern)) {
    try {
      const parsed: unknown = JSON.parse(match[2] ?? '');
      if (isAuthorSummary(parsed)) summaries.push(parsed);
    } catch {
      // Ignore malformed markers so a broken previous comment does not block rendering.
    }
  }

  return summaries;
}

function isAuthorSummary(value: unknown): value is AuthorSummary {
  if (!value || typeof value !== 'object') return false;
  const summary = value as Record<string, unknown>;

  return (
    typeof summary.login === 'string' &&
    typeof summary.totalCostUsd === 'number' &&
    typeof summary.inputTokens === 'number' &&
    typeof summary.outputTokens === 'number' &&
    typeof summary.sessionCount === 'number' &&
    Array.isArray(summary.models) &&
    summary.models.every((model) => typeof model === 'string') &&
    typeof summary.attributedPercent === 'number' &&
    typeof summary.lowConfidencePercent === 'number'
  );
}

function toAuthorSummary(author: RenderAuthorInput): AuthorSummary {
  return {
    login: author.login,
    totalCostUsd: author.totalCostUsd,
    inputTokens: author.inputTokens,
    outputTokens: author.outputTokens,
    sessionCount: author.sessionCount,
    models: author.models,
    attributedPercent: author.attributedPercent,
    lowConfidencePercent: author.lowConfidencePercent,
  };
}

function renderCurrentAuthorSection(author: RenderAuthorInput, summary: AuthorSummary): string[] {
  return [
    authorMarker(summary),
    `### @${author.login}`,
    '',
    renderSummaryLine(summary),
    '',
    renderModels(summary.models),
    '',
    '<details>',
    '<summary>Commit breakdown</summary>',
    '',
    '| Commit | Message | In | Out | Cost | Sessions |',
    '| --- | --- | ---: | ---: | ---: | ---: |',
    ...author.rows.map(
      (row) =>
        `| \`${truncateSha(row.sha)}\` | ${escapeTableCell(row.message)} | ${formatTokens(row.inputTokens)} | ${formatTokens(
          row.outputTokens,
        )} | ${formatCost(row.costUsd)} | ${row.sessionCount} |`,
    ),
    '',
    '</details>',
    '',
  ];
}

function renderAuthorSummarySection(summary: AuthorSummary): string[] {
  return [
    authorMarker(summary),
    `### @${summary.login}`,
    '',
    renderSummaryLine(summary),
    '',
    renderModels(summary.models),
    '',
  ];
}

function authorMarker(summary: AuthorSummary): string {
  return `<!-- prtokens:author:${summary.login} ${JSON.stringify(summary)} -->`;
}

function renderSummaryLine(summary: AuthorSummary): string {
  return `${formatTokens(summary.inputTokens)} in / ${formatTokens(summary.outputTokens)} out \u00b7 ${formatSessions(
    summary.sessionCount,
  )} \u00b7 ${summary.attributedPercent}% attributed \u00b7 ${summary.lowConfidencePercent}% low confidence`;
}

function renderModels(models: string[]): string {
  if (models.length === 0) return 'Models: none';
  return `Models: ${models.map((model) => `\`${model}\``).join(', ')}`;
}

function formatCost(costUsd: number): string {
  return `~$${costUsd.toFixed(2)}`;
}

function formatTokens(tokens: number): string {
  if (tokens === 0) return '0';
  if (tokens >= 1_000_000) return `${trimTrailingZero(tokens / 1_000_000)}M`;
  if (tokens >= 1_000) return `${trimTrailingZero(tokens / 1_000)}k`;
  return String(tokens);
}

function trimTrailingZero(value: number): string {
  return value.toFixed(1).replace(/\.0$/, '');
}

function formatSessions(sessionCount: number): string {
  return `${sessionCount} ${sessionCount === 1 ? 'session' : 'sessions'}`;
}

function truncateSha(sha: string): string {
  return sha.slice(0, 7);
}

function escapeTableCell(value: string): string {
  return value.replace(/\r?\n/g, '<br>').replace(/\|/g, '\\|');
}
